# Generated by Django 3.1.3 on 2021-03-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ENVIRONMENT_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='exercice_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='exercice_category',
            field=models.ManyToManyField(to='ENVIRONMENT_APP.Category'),
        ),
    ]
