# Generated by Django 3.1.3 on 2021-03-06 08:52

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ENVIRONMENT_APP', '0002_auto_20210304_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
