# Generated by Django 3.1.3 on 2021-03-06 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIRONMENT_APP', '0003_studentfile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
