# Generated by Django 3.1.3 on 2021-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIRONMENT_APP', '0004_auto_20210306_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
