# Generated by Django 3.1.3 on 2021-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIRONMENT_APP', '0006_auto_20210306_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfile',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='exercice_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
