# Generated by Django 3.1.3 on 2021-03-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIRONMENT_APP', '0007_auto_20210306_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
