# Generated by Django 3.1.3 on 2021-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENVIRONMENT_APP', '0009_auto_20210702_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
